"""
Markdown report export for scan results.

Used by the web UI (download / copy) and the CLI (`scan --markdown`).
"""

from __future__ import annotations

from models import ScanResult


def render_markdown_report(result: ScanResult) -> str:
    """Build a full Markdown compliance-style report from a ScanResult."""
    lines: list[str] = []
    title = f"{result.owner}/{result.repo}" if result.owner else result.url
    lines.append(f"# License scan: {title}")
    lines.append("")
    lines.append(f"- **URL:** {result.url or 'n/a'}")
    lines.append(f"- **Scanned at:** {result.scanned_at or 'n/a'}")
    lines.append(f"- **Repo license:** {result.repo_license or 'Unknown'}")
    lines.append(f"- **Primary language:** {result.primary_language or 'n/a'}")
    lines.append(
        f"- **Risk score:** {result.risk_score}/100 ({result.risk_score_label})"
    )
    lines.append(
        f"- **Scan complete:** {'Yes' if result.scan_complete else 'No (incomplete)'}"
    )
    lines.append(
        f"- **Can sell closed-source (heuristic):** "
        f"{'Possibly (with caveats)' if result.can_sell_closed and result.scan_complete else 'No / undetermined'}"
    )
    lines.append(
        f"- **Forces open source (heuristic):** {'Yes' if result.forces_open_source else 'No'}"
    )
    if result.has_network_copyleft:
        lines.append(
            "- **Network/SaaS copyleft signal (AGPL/SSPL):** Yes — review carefully"
        )
    if result.strong_copyleft_dev_only:
        lines.append(
            "- **Note:** Strong copyleft found only in dev/test dependencies"
        )
    lines.append(
        f"- **Packages:** {len(result.packages)} "
        f"(prod={result.prod_package_count}, dev={result.dev_package_count})"
    )
    lines.append("")

    lines.append("## Verdict")
    lines.append("")
    lines.append(result.verdict_summary or "_No verdict._")
    lines.append("")

    counts = result.risk_counts()
    prod_counts = result.risk_counts(prod_only=True)
    lines.append("## Risk summary")
    lines.append("")
    lines.append("| Category | All | Production only |")
    lines.append("|----------|-----|-----------------|")
    for key in ("permissive", "weak_copyleft", "strong_copyleft", "unknown"):
        lines.append(f"| {key} | {counts[key]} | {prod_counts[key]} |")
    lines.append("")

    if result.errors:
        lines.append("## Notes / errors")
        lines.append("")
        for err in result.errors:
            lines.append(f"- {err}")
        lines.append("")

    if result.deploy_advice:
        lines.append("## Deploy recommendations")
        lines.append("")
        for adv in result.deploy_advice:
            lines.append(f"### {adv.platform} (score {adv.score})")
            for reason in adv.reasons:
                lines.append(f"- {reason}")
            lines.append(f"- Docs: {adv.docs_url}")
            lines.append("")

    if result.replacements:
        lines.append("## Replacement suggestions")
        lines.append("")
        for rep in result.replacements:
            lines.append(
                f"- **{rep.package}** (`{rep.ecosystem}`, {rep.license_id or '?'})"
            )
            for alt in rep.alternatives:
                lines.append(f"  - → {alt}")
            if rep.note:
                lines.append(f"  - _{rep.note}_")
        lines.append("")

    lines.append("## Packages by license")
    lines.append("")
    if not result.packages:
        lines.append("_No packages resolved._")
        lines.append("")
    else:
        for lic, pkgs in result.grouped.items():
            lines.append(f"### {lic} ({len(pkgs)})")
            lines.append("")
            lines.append("| Package | Ecosystem | Scope | Risk | Source |")
            lines.append("|---------|-----------|-------|------|--------|")
            for p in sorted(pkgs, key=lambda x: (x.is_dev, x.name.lower())):
                scope = "dev" if p.is_dev else "prod"
                lines.append(
                    f"| {p.name} | {p.ecosystem} | {scope} | {p.risk} | "
                    f"`{p.source_file}` |"
                )
            lines.append("")

    if result.dependency_files:
        lines.append("## Dependency files analyzed")
        lines.append("")
        for path in result.dependency_files:
            lines.append(f"- `{path}`")
        lines.append("")

    lines.append("## Copyright notice")
    lines.append("")
    lines.append("```")
    lines.append((result.copyright_notice or "").rstrip())
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Legal disclaimer")
    lines.append("")
    lines.append(
        "This report is generated by **automated heuristics** for developer "
        "guidance only. It is **not legal advice**, not a license-compatibility "
        "opinion, and not a warranty of non-infringement or fitness for a "
        "particular purpose. Dual-licensing, linking models, SaaS/network use "
        "(AGPL/SSPL), additional permissions, CLA/DCO overlays, and contractual "
        "terms can change obligations. **Consult a qualified attorney** before "
        "commercial closed-source distribution or reliance on any verdict."
    )
    lines.append("")
    lines.append(
        "Copyright notice templates in this report are **not claims of ownership**. "
        "GitHub account names are not proof of copyright ownership."
    )
    lines.append("")
    lines.append(
        "_Generated by GitHub License Scanner. See docs/LEGAL_DISCLAIMER.md, "
        "docs/PRIVACY.md, and docs/TERMS.md._"
    )
    lines.append("")
    return "\n".join(lines)
